const PROGRAMS = [
  // ── Food & Nutrition ──
  {
    name: "SNAP (Food Stamps)",
    category: "food",
    categoryLabel: "Food & Nutrition",
    description: "The Supplemental Nutrition Assistance Program provides monthly benefits on an EBT card to purchase groceries. Benefits are based on household size, income, and expenses.",
    eligibility: "Gross monthly income at or below 130% of the federal poverty level. Net income at or below 100% of poverty. Assets below $2,750 (or $4,250 if a household member is elderly/disabled).",
    benefits: "Average benefit of $234/month per person. Can be used at grocery stores, farmers markets, and some online retailers.",
    howToApply: "Apply online through your state's SNAP portal, in person at your local SNAP office, or by mail.",
    website: "https://www.fns.usda.gov/snap/supplemental-nutrition-assistance-program",
    phone: "1-800-221-5689",
    tags: ["low-income", "food", "grocery", "ebt"],
    incomeLimit: 35000,
    forChildren: true,
    forSeniors: true,
    forDisabled: true,
    forVeterans: true,
    forUnemployed: true,
    forPregnant: true
  },
  {
    name: "WIC (Women, Infants & Children)",
    category: "food",
    categoryLabel: "Food & Nutrition",
    description: "Provides nutritious foods, nutrition education, breastfeeding support, and healthcare referrals for pregnant and postpartum women, infants, and children up to age 5.",
    eligibility: "Pregnant, breastfeeding, or postpartum women; infants and children under 5. Income at or below 185% of federal poverty level.",
    benefits: "Monthly food packages including milk, eggs, cereal, juice, fruits, vegetables, and infant formula. Nutrition counseling and healthcare referrals.",
    howToApply: "Contact your local WIC clinic or state WIC agency. Appointments can often be made online or by phone.",
    website: "https://www.fns.usda.gov/wic",
    phone: "Contact local WIC agency",
    tags: ["food", "nutrition", "women", "infants", "children", "pregnant"],
    incomeLimit: 50000,
    forChildren: true,
    forSeniors: false,
    forDisabled: false,
    forVeterans: true,
    forUnemployed: true,
    forPregnant: true
  },
  {
    name: "National School Lunch Program",
    category: "food",
    categoryLabel: "Food & Nutrition",
    description: "Provides free or reduced-price lunches to eligible children at participating schools and childcare institutions.",
    eligibility: "Children from families with incomes at or below 130% of poverty qualify for free meals; those between 130-185% qualify for reduced-price meals (no more than $0.40/lunch).",
    benefits: "Nutritionally balanced meals served daily at school. Free or at reduced price.",
    howToApply: "Complete an application through your child's school at the beginning of the school year.",
    website: "https://www.fns.usda.gov/nslp",
    phone: "Contact your child's school",
    tags: ["food", "children", "school", "lunch", "free meals"],
    incomeLimit: 50000,
    forChildren: true,
    forSeniors: false,
    forDisabled: false,
    forVeterans: false,
    forUnemployed: true,
    forPregnant: false
  },
  {
    name: "Meals on Wheels",
    category: "food",
    categoryLabel: "Food & Nutrition",
    description: "Delivers nutritious meals directly to the homes of seniors who are homebound or unable to prepare their own meals. Also provides friendly social contact and safety checks.",
    eligibility: "Generally available to adults 60 and older who are homebound or have difficulty preparing meals. No strict income requirements in most areas.",
    benefits: "Home-delivered meals (hot, frozen, or shelf-stable). Regular social contact and wellness checks.",
    howToApply: "Contact your local Meals on Wheels program or Area Agency on Aging.",
    website: "https://www.mealsonwheelsamerica.org",
    phone: "1-888-998-6325",
    tags: ["food", "seniors", "elderly", "home delivery", "meals"],
    incomeLimit: 100001,
    forChildren: false,
    forSeniors: true,
    forDisabled: true,
    forVeterans: true,
    forUnemployed: false,
    forPregnant: false
  },
  {
    name: "Community Food Banks",
    category: "food",
    categoryLabel: "Food & Nutrition",
    description: "Local food banks and food pantries provide free groceries and meals to individuals and families in need. Most operate on a no-questions-asked basis.",
    eligibility: "Open to anyone experiencing food insecurity. Most food banks do not require proof of income or identification.",
    benefits: "Free groceries including fresh produce, canned goods, bread, dairy, and sometimes prepared meals.",
    howToApply: "Visit FeedingAmerica.org to find a food bank near you. Walk-ins are typically welcome.",
    website: "https://www.feedingamerica.org/find-your-local-foodbank",
    phone: "1-800-771-2303",
    tags: ["food", "free", "pantry", "emergency", "groceries"],
    incomeLimit: 100001,
    forChildren: true,
    forSeniors: true,
    forDisabled: true,
    forVeterans: true,
    forUnemployed: true,
    forPregnant: true
  },

  // ── Housing ──
  {
    name: "Section 8 Housing Choice Voucher",
    category: "housing",
    categoryLabel: "Housing",
    description: "Provides rental assistance to low-income families, the elderly, and disabled individuals. Participants choose their own housing including apartments, townhouses, and single-family homes.",
    eligibility: "Income must not exceed 50% of area median income. Priority given to families at 30% or below area median income. U.S. citizenship or eligible immigration status required.",
    benefits: "Voucher pays the difference between 30% of the tenant's adjusted income and the approved rent amount. Participants choose where to live.",
    howToApply: "Apply through your local Public Housing Agency (PHA). Waiting lists are common due to high demand.",
    website: "https://www.hud.gov/topics/housing_choice_voucher_program_section_8",
    phone: "Contact local PHA",
    tags: ["housing", "rental", "voucher", "low-income", "rent assistance"],
    incomeLimit: 35000,
    forChildren: true,
    forSeniors: true,
    forDisabled: true,
    forVeterans: true,
    forUnemployed: true,
    forPregnant: true
  },
  {
    name: "Public Housing",
    category: "housing",
    categoryLabel: "Housing",
    description: "Affordable rental housing for eligible low-income families, the elderly, and persons with disabilities. Managed by local housing authorities.",
    eligibility: "Income limits vary by area, generally at or below 80% of area median income. Priority given to extremely low-income families.",
    benefits: "Reduced rent based on household income (generally 30% of adjusted income). Safe, decent, affordable housing.",
    howToApply: "Apply through your local Public Housing Agency. Check availability and waiting list status.",
    website: "https://www.hud.gov/topics/rental_assistance/phprog",
    phone: "Contact local housing authority",
    tags: ["housing", "rental", "affordable", "low-income", "public"],
    incomeLimit: 50000,
    forChildren: true,
    forSeniors: true,
    forDisabled: true,
    forVeterans: true,
    forUnemployed: true,
    forPregnant: true
  },
  {
    name: "LIHEAP (Energy Assistance)",
    category: "housing",
    categoryLabel: "Housing",
    description: "The Low Income Home Energy Assistance Program helps low-income households pay heating and cooling costs, and provides weatherization and energy-related home repairs.",
    eligibility: "Generally available to households with incomes at or below 150% of the federal poverty level or 60% of state median income.",
    benefits: "Direct payment to energy companies for heating/cooling bills. Emergency heating system repair/replacement. Weatherization services.",
    howToApply: "Contact your state or local LIHEAP office. Applications are typically accepted seasonally.",
    website: "https://www.acf.hhs.gov/ocs/low-income-home-energy-assistance-program-liheap",
    phone: "1-866-674-6327",
    tags: ["housing", "energy", "utilities", "heating", "cooling", "bills"],
    incomeLimit: 50000,
    forChildren: true,
    forSeniors: true,
    forDisabled: true,
    forVeterans: true,
    forUnemployed: true,
    forPregnant: true
  },
  {
    name: "Emergency Rental Assistance",
    category: "housing",
    categoryLabel: "Housing",
    description: "Provides direct financial assistance for rent and utility payments to eligible households experiencing financial hardship. Helps prevent eviction and homelessness.",
    eligibility: "Household income at or below 80% of area median income. Must demonstrate financial hardship or risk of homelessness/housing instability.",
    benefits: "Up to 12-18 months of rental assistance. Utility and home energy cost assistance. Housing stability services.",
    howToApply: "Contact your local or state emergency rental assistance program. Many accept applications online.",
    website: "https://home.treasury.gov/policy-issues/coronavirus/assistance-for-state-local-and-tribal-governments/emergency-rental-assistance-program",
    phone: "Contact local program",
    tags: ["housing", "rent", "emergency", "eviction prevention", "utilities"],
    incomeLimit: 50000,
    forChildren: true,
    forSeniors: true,
    forDisabled: true,
    forVeterans: true,
    forUnemployed: true,
    forPregnant: true
  },
  {
    name: "Habitat for Humanity",
    category: "housing",
    categoryLabel: "Housing",
    description: "Partners with families to build or improve affordable homes. Homeowners help build their own homes alongside volunteers and pay an affordable mortgage.",
    eligibility: "Based on level of need, willingness to partner (sweat equity hours), and ability to repay an affordable mortgage. Income requirements vary by location.",
    benefits: "Affordable homeownership with a no-interest mortgage. Home repairs and critical improvements for existing homeowners.",
    howToApply: "Contact your local Habitat for Humanity affiliate to learn about programs and apply.",
    website: "https://www.habitat.org",
    phone: "Contact local affiliate",
    tags: ["housing", "homeownership", "affordable", "mortgage", "building"],
    incomeLimit: 75000,
    forChildren: true,
    forSeniors: true,
    forDisabled: true,
    forVeterans: true,
    forUnemployed: false,
    forPregnant: false
  },

  // ── Healthcare ──
  {
    name: "Medicaid",
    category: "healthcare",
    categoryLabel: "Healthcare",
    description: "Provides free or low-cost health coverage to eligible low-income adults, children, pregnant women, elderly adults, and people with disabilities.",
    eligibility: "Eligibility varies by state. Generally available to adults with income up to 138% of the federal poverty level in expansion states. Children, pregnant women, and disabled individuals may qualify at higher income levels.",
    benefits: "Comprehensive health coverage including doctor visits, hospital stays, prescriptions, preventive care, mental health services, and long-term care.",
    howToApply: "Apply through HealthCare.gov, your state Medicaid agency, or at your local Department of Social Services.",
    website: "https://www.medicaid.gov",
    phone: "1-800-318-2596",
    tags: ["healthcare", "insurance", "medical", "low-income", "free"],
    incomeLimit: 35000,
    forChildren: true,
    forSeniors: true,
    forDisabled: true,
    forVeterans: true,
    forUnemployed: true,
    forPregnant: true
  },
  {
    name: "CHIP (Children's Health Insurance)",
    category: "healthcare",
    categoryLabel: "Healthcare",
    description: "Provides low-cost health coverage to children in families that earn too much to qualify for Medicaid but cannot afford private insurance.",
    eligibility: "Uninsured children under 19 in families with incomes too high for Medicaid. Income limits vary by state but can extend to 300%+ of the federal poverty level.",
    benefits: "Routine checkups, immunizations, doctor visits, prescriptions, dental and vision care, hospital care, lab tests, and emergency services.",
    howToApply: "Apply through HealthCare.gov or your state's CHIP program. Many states offer online applications.",
    website: "https://www.medicaid.gov/chip",
    phone: "1-877-543-7669",
    tags: ["healthcare", "children", "insurance", "kids", "medical"],
    incomeLimit: 75000,
    forChildren: true,
    forSeniors: false,
    forDisabled: false,
    forVeterans: false,
    forUnemployed: true,
    forPregnant: false
  },
  {
    name: "Community Health Centers",
    category: "healthcare",
    categoryLabel: "Healthcare",
    description: "Federally-funded health centers that provide primary care services on a sliding fee scale regardless of ability to pay or insurance status.",
    eligibility: "Open to everyone. Fees are based on a sliding scale determined by income and family size. No one is turned away for inability to pay.",
    benefits: "Primary care, dental, mental health, substance abuse treatment, pharmacy services. Fees adjusted based on income.",
    howToApply: "Visit FindAHealthCenter.hrsa.gov to locate a community health center near you.",
    website: "https://findahealthcenter.hrsa.gov",
    phone: "Call your nearest health center",
    tags: ["healthcare", "clinic", "dental", "mental health", "sliding scale", "free"],
    incomeLimit: 100001,
    forChildren: true,
    forSeniors: true,
    forDisabled: true,
    forVeterans: true,
    forUnemployed: true,
    forPregnant: true
  },
  {
    name: "Medicare",
    category: "healthcare",
    categoryLabel: "Healthcare",
    description: "Federal health insurance program primarily for people 65 and older. Also covers younger people with certain disabilities and people with End-Stage Renal Disease.",
    eligibility: "Adults 65 and older who are U.S. citizens or permanent residents. Younger adults with qualifying disabilities after 24 months of receiving Social Security disability benefits.",
    benefits: "Part A covers hospital stays; Part B covers doctor visits and outpatient care; Part D covers prescriptions. Medicare Advantage (Part C) offers bundled coverage through private plans.",
    howToApply: "Enroll online at SSA.gov, by calling Social Security, or at your local Social Security office. Enrollment begins 3 months before turning 65.",
    website: "https://www.medicare.gov",
    phone: "1-800-633-4227",
    tags: ["healthcare", "seniors", "insurance", "elderly", "disability"],
    incomeLimit: 100001,
    forChildren: false,
    forSeniors: true,
    forDisabled: true,
    forVeterans: true,
    forUnemployed: true,
    forPregnant: false
  },
  {
    name: "ACA Marketplace Insurance",
    category: "healthcare",
    categoryLabel: "Healthcare",
    description: "Health insurance plans available through the Affordable Care Act marketplace with income-based subsidies to reduce monthly premiums and out-of-pocket costs.",
    eligibility: "Available to U.S. citizens and legal residents not eligible for Medicare or affordable employer coverage. Premium subsidies available for incomes between 100-400% of the federal poverty level.",
    benefits: "Comprehensive health plans covering essential health benefits. Premium tax credits and cost-sharing reductions based on income.",
    howToApply: "Apply during Open Enrollment (Nov-Jan) at HealthCare.gov or your state's marketplace. Special enrollment periods available for qualifying life events.",
    website: "https://www.healthcare.gov",
    phone: "1-800-318-2596",
    tags: ["healthcare", "insurance", "ACA", "obamacare", "marketplace", "subsidized"],
    incomeLimit: 75000,
    forChildren: true,
    forSeniors: false,
    forDisabled: true,
    forVeterans: false,
    forUnemployed: true,
    forPregnant: true
  },

  // ── Financial Aid ──
  {
    name: "Earned Income Tax Credit (EITC)",
    category: "financial",
    categoryLabel: "Financial Aid",
    description: "A refundable tax credit for low-to-moderate income workers and families. The credit amount depends on income, filing status, and number of qualifying children.",
    eligibility: "Must have earned income and meet income limits (varies by filing status and number of children). Investment income must be below $11,000. Must be a U.S. citizen or resident alien.",
    benefits: "Tax credit up to $7,430 for families with 3+ children (2023). The credit reduces taxes owed and can result in a refund even if no taxes are owed.",
    howToApply: "Claim when filing your federal tax return (Form 1040). Free tax preparation available through VITA sites for eligible taxpayers.",
    website: "https://www.irs.gov/credits-deductions/individuals/earned-income-tax-credit-eitc",
    phone: "1-800-829-1040",
    tags: ["financial", "tax credit", "refund", "income", "EITC", "taxes"],
    incomeLimit: 75000,
    forChildren: true,
    forSeniors: true,
    forDisabled: true,
    forVeterans: true,
    forUnemployed: false,
    forPregnant: true
  },
  {
    name: "TANF (Temporary Assistance for Needy Families)",
    category: "financial",
    categoryLabel: "Financial Aid",
    description: "Provides temporary financial assistance and supportive services to low-income families with children. Designed to help families achieve self-sufficiency.",
    eligibility: "Families with children under 18 (or 19 if in school). Very low income (limits vary by state). Must participate in work activities or training.",
    benefits: "Monthly cash assistance, childcare assistance, job training and placement services, transportation assistance.",
    howToApply: "Apply through your state's human services or social services department. Online applications available in most states.",
    website: "https://www.acf.hhs.gov/ofa/programs/temporary-assistance-needy-families-tanf",
    phone: "Contact your state TANF office",
    tags: ["financial", "cash", "welfare", "families", "children", "temporary"],
    incomeLimit: 25000,
    forChildren: true,
    forSeniors: false,
    forDisabled: false,
    forVeterans: true,
    forUnemployed: true,
    forPregnant: true
  },
  {
    name: "Supplemental Security Income (SSI)",
    category: "financial",
    categoryLabel: "Financial Aid",
    description: "Monthly cash payments to people with limited income and resources who are 65 or older, blind, or disabled. Helps cover basic needs like food, clothing, and shelter.",
    eligibility: "Age 65+, blind, or disabled with limited income and resources (individual resources under $2,000; couples under $3,000).",
    benefits: "Maximum federal benefit of $914/month for individuals, $1,371 for couples (2023). Many states add a supplemental payment.",
    howToApply: "Apply online at SSA.gov, by calling Social Security, or at your local Social Security office.",
    website: "https://www.ssa.gov/ssi",
    phone: "1-800-772-1213",
    tags: ["financial", "disability", "seniors", "elderly", "blind", "cash", "SSI"],
    incomeLimit: 25000,
    forChildren: true,
    forSeniors: true,
    forDisabled: true,
    forVeterans: true,
    forUnemployed: true,
    forPregnant: false
  },
  {
    name: "Social Security Disability (SSDI)",
    category: "financial",
    categoryLabel: "Financial Aid",
    description: "Provides monthly benefits to people who can no longer work due to a significant medical condition expected to last at least one year or result in death.",
    eligibility: "Must have a qualifying disability and enough work credits from paying Social Security taxes. Work credits depend on age at time of disability.",
    benefits: "Monthly cash benefit based on lifetime earnings. Medicare coverage after 24 months. Dependents may also qualify for benefits.",
    howToApply: "Apply online at SSA.gov, by phone, or in person at your local Social Security office.",
    website: "https://www.ssa.gov/disability",
    phone: "1-800-772-1213",
    tags: ["financial", "disability", "SSDI", "cash", "insurance", "benefits"],
    incomeLimit: 100001,
    forChildren: false,
    forSeniors: true,
    forDisabled: true,
    forVeterans: true,
    forUnemployed: true,
    forPregnant: false
  },
  {
    name: "Child Tax Credit",
    category: "financial",
    categoryLabel: "Financial Aid",
    description: "A tax credit for families with qualifying children under 17. Reduces the amount of federal income tax owed and may provide a refund.",
    eligibility: "Families with children under 17 who are U.S. citizens. Income phase-out begins at $200,000 for single filers and $400,000 for married filing jointly.",
    benefits: "Up to $2,000 per qualifying child. Up to $1,600 is refundable (Additional Child Tax Credit) even if you owe no tax.",
    howToApply: "Claim when filing your federal tax return. Free filing options available through IRS Free File.",
    website: "https://www.irs.gov/credits-deductions/individuals/child-tax-credit",
    phone: "1-800-829-1040",
    tags: ["financial", "tax credit", "children", "families", "refund"],
    incomeLimit: 100001,
    forChildren: true,
    forSeniors: false,
    forDisabled: false,
    forVeterans: true,
    forUnemployed: true,
    forPregnant: false
  },

  // ── Employment ──
  {
    name: "Unemployment Insurance",
    category: "employment",
    categoryLabel: "Employment",
    description: "Provides temporary income to workers who have lost their jobs through no fault of their own while they search for new employment.",
    eligibility: "Must have lost your job through no fault of your own (layoff, reduction in force). Must have earned enough wages during a base period. Must be actively seeking work.",
    benefits: "Weekly benefit amount varies by state and prior earnings (typically 40-50% of previous wages up to a state maximum). Benefits usually last up to 26 weeks.",
    howToApply: "File a claim with your state's unemployment insurance program. Most states offer online filing.",
    website: "https://www.careeronestop.org/LocalHelp/UnemploymentBenefits/find-unemployment-benefits.aspx",
    phone: "Contact your state UI office",
    tags: ["employment", "unemployment", "job loss", "income", "insurance"],
    incomeLimit: 100001,
    forChildren: false,
    forSeniors: true,
    forDisabled: false,
    forVeterans: true,
    forUnemployed: true,
    forPregnant: false
  },
  {
    name: "American Job Centers (CareerOneStop)",
    category: "employment",
    categoryLabel: "Employment",
    description: "Free career services including job search assistance, resume writing, interview preparation, skills training, and connections to employers.",
    eligibility: "Open to all job seekers. Additional services (like paid training) may have income or other requirements.",
    benefits: "Job search assistance, career counseling, resume and interview help, skills assessments, referrals to training programs, access to computers and job listings.",
    howToApply: "Visit your local American Job Center. Find locations at CareerOneStop.org.",
    website: "https://www.careeronestop.org",
    phone: "1-877-348-0502",
    tags: ["employment", "jobs", "career", "training", "resume", "free"],
    incomeLimit: 100001,
    forChildren: false,
    forSeniors: true,
    forDisabled: true,
    forVeterans: true,
    forUnemployed: true,
    forPregnant: false
  },
  {
    name: "Job Corps",
    category: "employment",
    categoryLabel: "Employment",
    description: "Free education and vocational training program for young people ages 16-24. Offers hands-on career training in over 100 career areas along with housing and meals.",
    eligibility: "Ages 16-24, U.S. citizen or legal resident, low-income (meet income requirements). Must be free of serious behavioral issues.",
    benefits: "Free career and technical training, high school diploma or GED, college credits, housing and meals, healthcare, driver's education, job placement assistance.",
    howToApply: "Apply online at JobCorps.gov or call to speak with an admissions counselor.",
    website: "https://www.jobcorps.gov",
    phone: "1-800-733-5627",
    tags: ["employment", "youth", "training", "education", "free", "vocational"],
    incomeLimit: 35000,
    forChildren: false,
    forSeniors: false,
    forDisabled: false,
    forVeterans: false,
    forUnemployed: true,
    forPregnant: false
  },
  {
    name: "WIOA Adult & Dislocated Worker Programs",
    category: "employment",
    categoryLabel: "Employment",
    description: "Workforce Innovation and Opportunity Act programs provide job training, education, and employment services to adults and workers who have been laid off.",
    eligibility: "Adults 18+ authorized to work in the U.S. Priority given to low-income individuals, public assistance recipients, and veterans. Dislocated workers who lost jobs due to closures or layoffs.",
    benefits: "Occupational skills training, on-the-job training, apprenticeships, adult education, career counseling, and supportive services.",
    howToApply: "Contact your local American Job Center or workforce development board.",
    website: "https://www.dol.gov/agencies/eta/wioa",
    phone: "1-877-872-5627",
    tags: ["employment", "training", "workforce", "career", "laid off", "adult education"],
    incomeLimit: 75000,
    forChildren: false,
    forSeniors: true,
    forDisabled: true,
    forVeterans: true,
    forUnemployed: true,
    forPregnant: false
  },

  // ── Education ──
  {
    name: "Federal Pell Grants",
    category: "education",
    categoryLabel: "Education",
    description: "Need-based grants for undergraduate students that do not have to be repaid. The foundation of federal student financial aid.",
    eligibility: "Undergraduate students who have not earned a bachelor's degree and demonstrate financial need. Must be a U.S. citizen or eligible noncitizen.",
    benefits: "Up to $7,395 per year (2023-24). Amount depends on financial need, cost of attendance, and enrollment status (full or part-time).",
    howToApply: "Complete the Free Application for Federal Student Aid (FAFSA) at StudentAid.gov.",
    website: "https://studentaid.gov/understand-aid/types/grants/pell",
    phone: "1-800-433-3243",
    tags: ["education", "college", "grant", "financial aid", "tuition", "free money"],
    incomeLimit: 75000,
    forChildren: false,
    forSeniors: true,
    forDisabled: true,
    forVeterans: true,
    forUnemployed: true,
    forPregnant: true
  },
  {
    name: "Head Start & Early Head Start",
    category: "education",
    categoryLabel: "Education",
    description: "Comprehensive early childhood education programs for low-income children from birth to age 5 and pregnant women. Includes education, health, nutrition, and parent involvement services.",
    eligibility: "Children from birth to age 5 in families at or below the federal poverty level. Also eligible: children in foster care, homeless children, and families receiving public assistance.",
    benefits: "Free preschool education, health screenings, nutritious meals, social services, and parenting support. Early Head Start serves infants, toddlers, and pregnant women.",
    howToApply: "Contact your local Head Start program. Use the Head Start Locator at ECLKC.ohs.acf.hhs.gov.",
    website: "https://www.acf.hhs.gov/ohs",
    phone: "1-866-763-6481",
    tags: ["education", "preschool", "children", "early childhood", "free", "daycare"],
    incomeLimit: 35000,
    forChildren: true,
    forSeniors: false,
    forDisabled: false,
    forVeterans: true,
    forUnemployed: true,
    forPregnant: true
  },
  {
    name: "Adult Education & GED Programs",
    category: "education",
    categoryLabel: "Education",
    description: "Free or low-cost programs to help adults earn a high school equivalency diploma (GED/HiSET), improve literacy, or learn English as a second language (ESL).",
    eligibility: "Adults 16+ who are not enrolled in school and lack a high school diploma. ESL programs open to adults with limited English proficiency.",
    benefits: "Free GED preparation classes, ESL/ESOL classes, basic literacy instruction, and career readiness skills. Testing fee assistance available in some areas.",
    howToApply: "Contact your local adult education center, community college, or library for program information.",
    website: "https://www.ed.gov/category/program/adult-education-basic-grants-states",
    phone: "Contact local adult education center",
    tags: ["education", "GED", "adult", "literacy", "ESL", "English", "free"],
    incomeLimit: 100001,
    forChildren: false,
    forSeniors: true,
    forDisabled: true,
    forVeterans: true,
    forUnemployed: true,
    forPregnant: false
  },

  // ── Family & Children ──
  {
    name: "Child Care Assistance (CCDF)",
    category: "family",
    categoryLabel: "Family & Children",
    description: "Helps low-income families pay for child care so parents can work, attend school, or participate in training. Administered through the Child Care and Development Fund.",
    eligibility: "Families with children under 13 (or under 19 for special needs). Parents must be working, in school, or in job training. Income limits vary by state.",
    benefits: "Subsidized child care payments directly to child care providers. Copayments based on income and family size.",
    howToApply: "Contact your state or local child care resource and referral agency. Apply through your state's human services department.",
    website: "https://www.acf.hhs.gov/occ/ccdf-reauthorization",
    phone: "1-800-616-2242",
    tags: ["family", "childcare", "daycare", "children", "working parents", "subsidy"],
    incomeLimit: 50000,
    forChildren: true,
    forSeniors: false,
    forDisabled: false,
    forVeterans: true,
    forUnemployed: false,
    forPregnant: false
  },
  {
    name: "Child Support Enforcement",
    category: "family",
    categoryLabel: "Family & Children",
    description: "Helps parents locate noncustodial parents, establish paternity, establish and enforce child support orders, and collect child support payments.",
    eligibility: "Any parent (custodial or noncustodial) can request services. Available regardless of income.",
    benefits: "Locating absent parents, establishing paternity, establishing support orders, collecting and distributing payments, modifying orders when circumstances change.",
    howToApply: "Apply through your state or local child support enforcement office.",
    website: "https://www.acf.hhs.gov/css",
    phone: "Contact your state CSE office",
    tags: ["family", "child support", "children", "enforcement", "paternity"],
    incomeLimit: 100001,
    forChildren: true,
    forSeniors: false,
    forDisabled: false,
    forVeterans: true,
    forUnemployed: true,
    forPregnant: false
  },
  {
    name: "Foster Care & Adoption Assistance",
    category: "family",
    categoryLabel: "Family & Children",
    description: "Provides support for children in foster care and families who adopt children from the foster care system, including financial assistance and services.",
    eligibility: "Children who cannot safely remain with their families. Adoption assistance for families adopting children with special needs from foster care.",
    benefits: "Foster care payments to cover child's expenses. Adoption assistance including monthly payments, Medicaid coverage, and support services. Independent living services for youth aging out.",
    howToApply: "Contact your local child welfare agency or Department of Children and Family Services.",
    website: "https://www.childwelfare.gov",
    phone: "1-800-394-3366",
    tags: ["family", "foster care", "adoption", "children", "youth"],
    incomeLimit: 100001,
    forChildren: true,
    forSeniors: false,
    forDisabled: false,
    forVeterans: false,
    forUnemployed: false,
    forPregnant: false
  },
  {
    name: "Family Violence Prevention Services",
    category: "family",
    categoryLabel: "Family & Children",
    description: "Provides shelter, crisis hotlines, counseling, and supportive services for survivors of domestic violence, dating violence, and family violence.",
    eligibility: "Anyone experiencing domestic violence, dating violence, stalking, or family violence. No income requirements.",
    benefits: "Emergency shelter, 24/7 crisis hotlines, safety planning, counseling, legal advocacy, children's services, and transitional housing.",
    howToApply: "Call the National Domestic Violence Hotline for immediate help and local referrals.",
    website: "https://www.thehotline.org",
    phone: "1-800-799-7233",
    tags: ["family", "domestic violence", "shelter", "safety", "crisis", "abuse"],
    incomeLimit: 100001,
    forChildren: true,
    forSeniors: true,
    forDisabled: true,
    forVeterans: true,
    forUnemployed: true,
    forPregnant: true
  },

  // ── Seniors ──
  {
    name: "Senior Community Service Employment (SCSEP)",
    category: "seniors",
    categoryLabel: "Seniors",
    description: "Provides part-time community service training and employment for low-income, unemployed seniors. Helps older workers build skills and transition to permanent employment.",
    eligibility: "Age 55+, unemployed, and household income at or below 125% of the federal poverty level.",
    benefits: "Part-time paid training at community service organizations. Skills training, job search assistance, and support transitioning to permanent employment.",
    howToApply: "Contact your local American Job Center or Area Agency on Aging.",
    website: "https://www.dol.gov/agencies/eta/seniors",
    phone: "1-877-872-5627",
    tags: ["seniors", "employment", "training", "elderly", "job", "part-time"],
    incomeLimit: 25000,
    forChildren: false,
    forSeniors: true,
    forDisabled: false,
    forVeterans: true,
    forUnemployed: true,
    forPregnant: false
  },
  {
    name: "Area Agency on Aging Services",
    category: "seniors",
    categoryLabel: "Seniors",
    description: "Local agencies that provide a wide range of services to help older adults live independently, including meals, transportation, caregiver support, and information & referral.",
    eligibility: "Generally available to adults 60 and older. Some services may prioritize low-income, minority, or socially isolated seniors.",
    benefits: "Home-delivered and congregate meals, transportation, caregiver support, health promotion, elder abuse prevention, legal assistance, and benefits counseling.",
    howToApply: "Contact the Eldercare Locator to find your local Area Agency on Aging.",
    website: "https://eldercare.acl.gov",
    phone: "1-800-677-1116",
    tags: ["seniors", "aging", "elderly", "transportation", "caregiver", "meals", "independent"],
    incomeLimit: 100001,
    forChildren: false,
    forSeniors: true,
    forDisabled: true,
    forVeterans: true,
    forUnemployed: false,
    forPregnant: false
  },
  {
    name: "Medicare Savings Programs",
    category: "seniors",
    categoryLabel: "Seniors",
    description: "State programs that help people with limited income and resources pay Medicare premiums, deductibles, coinsurance, and copayments.",
    eligibility: "Must be enrolled in Medicare Part A. Income and resource limits vary by program level. Generally for individuals with incomes below 135% of the federal poverty level.",
    benefits: "Payment of Medicare premiums, deductibles, and coinsurance depending on the program level. Also may automatically qualify you for Extra Help with prescription drug costs.",
    howToApply: "Apply through your state Medicaid office.",
    website: "https://www.medicare.gov/your-medicare-costs/get-help-paying-costs/medicare-savings-programs",
    phone: "1-800-633-4227",
    tags: ["seniors", "medicare", "healthcare", "premiums", "savings", "elderly"],
    incomeLimit: 25000,
    forChildren: false,
    forSeniors: true,
    forDisabled: true,
    forVeterans: true,
    forUnemployed: true,
    forPregnant: false
  },

  // ── Disability ──
  {
    name: "Vocational Rehabilitation Services",
    category: "disability",
    categoryLabel: "Disability",
    description: "Provides individualized services to help people with disabilities prepare for, obtain, maintain, or advance in employment.",
    eligibility: "Individuals with physical or mental disabilities that result in a substantial impediment to employment. Must require VR services to achieve an employment outcome.",
    benefits: "Career counseling, job training, assistive technology, job placement, supported employment, and other services tailored to individual needs.",
    howToApply: "Contact your state's vocational rehabilitation agency.",
    website: "https://rsa.ed.gov",
    phone: "Contact your state VR agency",
    tags: ["disability", "employment", "training", "rehabilitation", "vocational", "assistive technology"],
    incomeLimit: 100001,
    forChildren: false,
    forSeniors: true,
    forDisabled: true,
    forVeterans: true,
    forUnemployed: true,
    forPregnant: false
  },
  {
    name: "ABLE Accounts (Achieving a Better Life Experience)",
    category: "disability",
    categoryLabel: "Disability",
    description: "Tax-advantaged savings accounts for individuals with disabilities that allow saving without jeopardizing eligibility for public benefits like SSI and Medicaid.",
    eligibility: "Individuals with a disability that began before age 26 (increasing to 46 starting 2026). Must meet Social Security's definition of disability or be eligible for a disability tax credit.",
    benefits: "Save up to $18,000/year tax-free. Funds can be used for disability-related expenses including education, housing, transportation, health, and assistive technology.",
    howToApply: "Open an account through your state's ABLE program or any state that accepts out-of-state residents.",
    website: "https://www.ablenrc.org",
    phone: "Contact your state ABLE program",
    tags: ["disability", "savings", "financial", "tax-free", "benefits"],
    incomeLimit: 100001,
    forChildren: true,
    forSeniors: true,
    forDisabled: true,
    forVeterans: true,
    forUnemployed: true,
    forPregnant: false
  },
  {
    name: "Assistive Technology Programs",
    category: "disability",
    categoryLabel: "Disability",
    description: "State programs that help people with disabilities access assistive technology devices and services, including device demonstrations, short-term loans, and financing programs.",
    eligibility: "Individuals with disabilities of all ages. Programs serve people regardless of income or type of disability.",
    benefits: "Device demonstrations and loans, financial assistance for purchasing AT devices, equipment reuse/exchange programs, and training on assistive technology.",
    howToApply: "Contact your state's Assistive Technology Act program.",
    website: "https://www.at3center.net/stateprogram",
    phone: "Contact your state AT program",
    tags: ["disability", "technology", "assistive", "devices", "equipment", "accessibility"],
    incomeLimit: 100001,
    forChildren: true,
    forSeniors: true,
    forDisabled: true,
    forVeterans: true,
    forUnemployed: true,
    forPregnant: false
  },

  // ── Veterans ──
  {
    name: "VA Health Care",
    category: "veterans",
    categoryLabel: "Veterans",
    description: "Comprehensive healthcare services for eligible veterans through the Veterans Health Administration, one of the largest healthcare systems in the United States.",
    eligibility: "Veterans who served in active military service and were discharged under conditions other than dishonorable. Priority given based on service-connected disabilities and income.",
    benefits: "Primary care, specialty care, mental health services, prescriptions, preventive care, urgent/emergency care. Some veterans may have copays based on priority group.",
    howToApply: "Apply online at VA.gov, by phone, or in person at your local VA health facility.",
    website: "https://www.va.gov/health-care",
    phone: "1-877-222-8387",
    tags: ["veterans", "healthcare", "VA", "medical", "military"],
    incomeLimit: 100001,
    forChildren: false,
    forSeniors: true,
    forDisabled: true,
    forVeterans: true,
    forUnemployed: true,
    forPregnant: false
  },
  {
    name: "VA Disability Compensation",
    category: "veterans",
    categoryLabel: "Veterans",
    description: "Tax-free monetary benefit paid to veterans with disabilities that are the result of a disease or injury incurred or aggravated during active military service.",
    eligibility: "Veterans with a service-connected disability rated at 10% or higher. Must have served on active duty, active duty for training, or inactive duty training.",
    benefits: "Monthly tax-free payments ranging from ~$165 to $3,737+ depending on disability rating. Additional amounts for dependents at 30%+ rating.",
    howToApply: "File a claim online at VA.gov, through a Veterans Service Organization, or at your local VA office.",
    website: "https://www.va.gov/disability",
    phone: "1-800-827-1000",
    tags: ["veterans", "disability", "compensation", "military", "service-connected"],
    incomeLimit: 100001,
    forChildren: false,
    forSeniors: true,
    forDisabled: true,
    forVeterans: true,
    forUnemployed: true,
    forPregnant: false
  },
  {
    name: "GI Bill Education Benefits",
    category: "veterans",
    categoryLabel: "Veterans",
    description: "Education and training benefits for veterans, service members, and eligible dependents. Covers tuition, housing, books, and supplies for college, graduate school, and training programs.",
    eligibility: "Veterans with at least 90 days of aggregate active duty service after September 10, 2001 (Post-9/11 GI Bill). Other GI Bill programs have different service requirements.",
    benefits: "Full tuition at public schools (or up to ~$27,120/year at private schools), monthly housing allowance, books and supplies stipend up to $1,000/year.",
    howToApply: "Apply online at VA.gov. Compare your benefits using the GI Bill Comparison Tool.",
    website: "https://www.va.gov/education",
    phone: "1-888-442-4551",
    tags: ["veterans", "education", "college", "GI Bill", "tuition", "training"],
    incomeLimit: 100001,
    forChildren: false,
    forSeniors: false,
    forDisabled: false,
    forVeterans: true,
    forUnemployed: true,
    forPregnant: false
  },
  {
    name: "VA Home Loan Guarantee",
    category: "veterans",
    categoryLabel: "Veterans",
    description: "Helps veterans, active duty service members, and eligible surviving spouses become homeowners by providing a home loan guarantee requiring no down payment.",
    eligibility: "Veterans, active duty service members with at least 90 days of service, National Guard/Reserve members with 6+ years of service, and eligible surviving spouses.",
    benefits: "No down payment required, no private mortgage insurance, competitive interest rates, limited closing costs, and no prepayment penalties.",
    howToApply: "Obtain a Certificate of Eligibility through VA.gov, then work with a VA-approved lender.",
    website: "https://www.va.gov/housing-assistance/home-loans",
    phone: "1-877-827-3702",
    tags: ["veterans", "housing", "home loan", "mortgage", "military", "homeownership"],
    incomeLimit: 100001,
    forChildren: false,
    forSeniors: true,
    forDisabled: true,
    forVeterans: true,
    forUnemployed: false,
    forPregnant: false
  },
  {
    name: "Veterans Pension",
    category: "veterans",
    categoryLabel: "Veterans",
    description: "Tax-free monetary benefit for low-income wartime veterans who are 65+ or permanently disabled. Aid and Attendance benefits available for those needing regular help.",
    eligibility: "Wartime veterans age 65+ or permanently disabled. Must have limited income and net worth. At least 90 days of active duty with at least one day during wartime.",
    benefits: "Monthly pension payments based on income. Enhanced rates through Aid & Attendance or Housebound benefits for those needing help with daily activities.",
    howToApply: "Apply online at VA.gov, through a Veterans Service Organization, or by mail.",
    website: "https://www.va.gov/pension",
    phone: "1-800-827-1000",
    tags: ["veterans", "pension", "financial", "wartime", "elderly", "aid and attendance"],
    incomeLimit: 25000,
    forChildren: false,
    forSeniors: true,
    forDisabled: true,
    forVeterans: true,
    forUnemployed: true,
    forPregnant: false
  },

  // ── Public Transit ──
  {
    name: "Reduced Fare Transit Programs",
    category: "transit",
    categoryLabel: "Public Transit",
    description: "Most public transit agencies offer reduced fare programs for seniors, people with disabilities, and Medicare cardholders. Typical discounts are 50% or more off regular fares.",
    eligibility: "Generally available to seniors (65+), people with disabilities, and Medicare cardholders. Some agencies also offer reduced fares for students and low-income riders.",
    benefits: "Half-price or greater discounts on bus, subway, light rail, and commuter rail fares. Reduced-fare ID cards accepted across transit systems.",
    howToApply: "Contact your local transit agency to apply for a reduced-fare card. Typically requires proof of age, disability, or Medicare enrollment.",
    website: "https://www.transit.dot.gov",
    phone: "Contact your local transit agency",
    tags: ["transit", "bus", "subway", "reduced fare", "discount", "transportation"],
    incomeLimit: 100001,
    forChildren: false,
    forSeniors: true,
    forDisabled: true,
    forVeterans: true,
    forUnemployed: false,
    forPregnant: false
  },
  {
    name: "Section 5310 - Transit for Seniors & Disabled",
    category: "transit",
    categoryLabel: "Public Transit",
    description: "Federal program that provides funding for transportation services specifically designed for elderly individuals and persons with disabilities, including paratransit and demand-response services.",
    eligibility: "Seniors (65+) and individuals with disabilities who are unable to use fixed-route public transit. Particularly serves areas where public transit is unavailable or insufficient.",
    benefits: "Door-to-door paratransit service, demand-response shuttle services, accessible vehicles, and mobility management programs.",
    howToApply: "Services are provided through local transit agencies and nonprofit organizations. Contact your Area Agency on Aging or local transit authority.",
    website: "https://www.transit.dot.gov/funding/grants/enhanced-mobility-seniors-individuals-disabilities-section-5310",
    phone: "Contact local transit agency",
    tags: ["transit", "seniors", "disability", "paratransit", "door-to-door", "accessible"],
    incomeLimit: 100001,
    forChildren: false,
    forSeniors: true,
    forDisabled: true,
    forVeterans: true,
    forUnemployed: false,
    forPregnant: false
  },
  {
    name: "Medicaid Non-Emergency Medical Transportation (NEMT)",
    category: "transit",
    categoryLabel: "Public Transit",
    description: "Provides free transportation to and from medical appointments for Medicaid beneficiaries who have no other means of transportation. Required in all states under federal law.",
    eligibility: "Medicaid recipients who need transportation to medical appointments and have no other way to get there. Available in all states.",
    benefits: "Free rides to doctor appointments, pharmacies, hospitals, therapy sessions, and other medical services. Includes bus passes, taxi vouchers, van services, and mileage reimbursement.",
    howToApply: "Contact your state Medicaid agency or managed care plan to arrange transportation, usually 48-72 hours before your appointment.",
    website: "https://www.medicaid.gov/medicaid/benefits/nonemergency-medical-transportation/index.html",
    phone: "Contact your Medicaid plan",
    tags: ["transit", "medical", "Medicaid", "transportation", "free rides", "doctor"],
    incomeLimit: 35000,
    forChildren: true,
    forSeniors: true,
    forDisabled: true,
    forVeterans: true,
    forUnemployed: true,
    forPregnant: true
  },
  {
    name: "Job Access & Reverse Commute (JARC) Programs",
    category: "transit",
    categoryLabel: "Public Transit",
    description: "Transit services designed to connect low-income workers with jobs that may not be easily accessible by existing public transit, including routes to suburban employment centers and late-night/weekend service.",
    eligibility: "Low-income individuals who need transportation to access employment opportunities. Particularly targets areas with limited transit service.",
    benefits: "New or expanded bus routes to employment centers, late-night and weekend service, vanpool programs, and guaranteed ride home programs.",
    howToApply: "Check with your local transit agency or workforce development board for available services in your area.",
    website: "https://www.transit.dot.gov",
    phone: "Contact local transit agency or 211",
    tags: ["transit", "employment", "commute", "low-income", "job access", "bus"],
    incomeLimit: 50000,
    forChildren: false,
    forSeniors: true,
    forDisabled: true,
    forVeterans: true,
    forUnemployed: true,
    forPregnant: false
  },
  {
    name: "Veterans Transportation Service (VTS)",
    category: "transit",
    categoryLabel: "Public Transit",
    description: "Provides free transportation for eligible veterans to and from VA medical facilities. Includes direct transport by VA vehicles and partnerships with volunteer driver programs like DAV.",
    eligibility: "Veterans enrolled in VA health care who need transportation to VA medical appointments. Priority given to veterans with service-connected disabilities and those with limited mobility.",
    benefits: "Free rides to VA medical centers and clinics. Includes VA shuttle buses, volunteer driver programs (DAV), beneficiary travel mileage reimbursement, and special mode transport.",
    howToApply: "Contact your local VA medical center's Veteran Transportation Service or the DAV Transportation Network.",
    website: "https://www.va.gov/healthbenefits/vtp",
    phone: "Contact your local VA medical center",
    tags: ["transit", "veterans", "VA", "medical", "free rides", "transportation"],
    incomeLimit: 100001,
    forChildren: false,
    forSeniors: true,
    forDisabled: true,
    forVeterans: true,
    forUnemployed: true,
    forPregnant: false
  },
  {
    name: "Low-Income Transit Pass Programs",
    category: "transit",
    categoryLabel: "Public Transit",
    description: "Many cities and transit agencies offer discounted or free transit passes for low-income residents. These programs make daily commuting affordable for people below certain income thresholds.",
    eligibility: "Varies by city/agency. Typically available to residents with household income below 200% of the federal poverty level. Some programs require enrollment in other assistance programs.",
    benefits: "Free or heavily discounted monthly transit passes (often 50-80% off). Covers bus, rail, subway, and sometimes ride-share credits.",
    howToApply: "Check with your local transit agency for income-based fare programs. Many require proof of income or enrollment in SNAP, Medicaid, or other assistance programs.",
    website: "https://www.apta.com",
    phone: "Contact your local transit agency or 211",
    tags: ["transit", "bus pass", "low-income", "discount", "monthly pass", "affordable"],
    incomeLimit: 50000,
    forChildren: false,
    forSeniors: true,
    forDisabled: true,
    forVeterans: true,
    forUnemployed: true,
    forPregnant: true
  }
];
